# version: "3.7"

services:
  gateway:
    build:
      context: ./gateway

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/config-core_demo.json:/usr/share/nginx/html/config-core_demo.json

  backend:
    volumes:
      - ./distro/configuration/backend_configuration:/openmrs/distribution/openmrs_config
