services:

  gateway:
    image: openmrs/openmrs-reference-application-3-gateway:${TAG:-qa}
    restart: "unless-stopped"
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"


  frontend:
    image: openmrs/openmrs-reference-application-3-frontend:${TAG:-qa}
    restart: "unless-stopped"

    environment:
      SPA_PATH: /openmrs/spa
      API_URL: /openmrs
      SPA_CONFIG_URLS: /openmrs/spa/config-core_demo.json
      SPA_DEFAULT_LOCALE:

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      timeout: 5s

    depends_on:
      - backend


  backend:
    image: openmrs/openmrs-reference-application-3-backend:${TAG:-qa}
    restart: "unless-stopped"

    environment:

      OMRS_CONFIG_MODULE_WEB_ADMIN: "true"

      # Permite actualizar la estructura de la DB si es necesario
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"

      # Crear tablas si la DB está vacía
      OMRS_CONFIG_CREATE_TABLES: "true"


      # DATOS DE LA VPS MYSQL
      OMRS_CONFIG_CONNECTION_SERVER: 179.197.234.35
      OMRS_CONFIG_CONNECTION_DATABASE: openmrs
      OMRS_CONFIG_CONNECTION_USERNAME: openmrs
      OMRS_CONFIG_CONNECTION_PASSWORD: 1234


    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      timeout: 5s


    volumes:
      - openmrs-data:/openmrs/data
volumes:
  openmrs-data: